---
# Simple debug play that calls a basic debug task

- name: debug::debug
  hosts:
    - all
    - '!tags_legacy'
  tags:
    - debug::debug
  gather_facts: yes
  tasks:
    - debug:
        msg: "Hello from debug play"
