---
# Configuration plays for most devices

- name: base::configure:hostname
  hosts:
    - all
    - '!tags_legacy'
  tags:
    - base::configuration:hostname
  gather_facts: yes
  roles:
    - name: adfinis-sygroup.hostname

- name: base::configure:timesync
  hosts:
    - all
    - '!tags_legacy'
    # don't manage timesync on ovirt nodes since the should be peering with each other
    # See https://github.com/linux-system-roles/timesync/pull/46 for what is needed to
    # manage ntp in peering mode on affected nodes
    - '!tags_ovirt'
  tags:
    - base::configure:timesync
  gather_facts: yes
  roles:
    - name: linux-system-roles.timesync

- name: base::configure:kdump
  hosts:
    - all
    - '!tags_legacy'
  tags:
    - base::configure:kdump
  gather_facts: yes
  roles:
    - name: linux-system-roles.kdump

- name: base::configure:abrt
  hosts:
    - all
    - '!tags_legacy'
  tags:
    - base::configure:abrt
  roles:
    - name: abrt.abrt-client-role
