---
# Configuration plays for live-studio laptops and devices

- name: live-studio::configure
  hosts:
    - tags_outside_nodes
  tags:
    - live-studio::configure
  gather_facts: yes
  roles:
    - name: radiorabe.motion
      motion_preflight: off
      motion_install: off
      motion_configure: on
