---
# Install plays for live-studio laptops and devices

- hosts:
    - tags_outside_nodes
  gather_facts: yes
  roles:
    - name: radiorabe.motion
      motion_preflight: off
      motion_install: on
      motion_configure: off
