---
# Install plays for live-studio laptops and devices

- name: live-studio::install
  hosts:
    - tags_outside_nodes
  tags:
    - live-studio::install
  gather_facts: yes
  roles:
    - name: radiorabe.motion
      motion_preflight: off
      motion_install: on
      motion_configure: off
